### ISSUE TITLE
Misuses of cryptographic APIs

### ISSUE THREAD

**Issue by mhp0rtal** [yawkat/dbus-java#2]
Hi
The following lines have cryptographic API misuses. <br> File name => dbus-protocol/src/main/java/at/yawk/dbus/protocol/auth/mechanism/DbusCookieSha1AuthMechanism.java: Line number => 91: API name => MessageDigest:<BR> File name => dbus-protocol/src/main/java/at/yawk/dbus/protocol/auth/mechanism/DbusCookieSha1AuthMechanism.java: Line number => 90: API name => MessageDigest:First parameter (with value "SHA1") should be any of {SHA-256, SHA-384, SHA-512}<BR> File name => dbus-protocol/src/main/java/at/yawk/dbus/protocol/auth/mechanism/DbusCookieSha1AuthMechanism.java: Line number => 91: API name => MessageDigest:<BR>

**Comment by yawkat** [comment]
Tell that to dbus.
